### ISSUE TITLE
Module does not work with require()

### ISSUE THREAD

**Issue by joepie91** [joeltg/big-varint#1]
Requiring this module like so:

```js
const bigVarint = require("big-varint");
```

... produces the following error:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/sven/projects/zapdb-kv/node_modules/big-varint/lib/index.js
require() of ES modules is not supported.
require() of /home/sven/projects/zapdb-kv/node_modules/big-varint/lib/index.js from /home/sven/projects/zapdb-kv/src/storage-encoder/encode.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/sven/projects/zapdb-kv/node_modules/big-varint/package.json.
```

Unfortunately, while it's possible to import CJS modules from ESM code, the other way around is not possible (or at least not when using `"type": "module"`), so for maximum compatibility a library should use CJS-compatible exports.

**Comment by joeltg** [comment]
> so for maximum compatibility a library should use CJS-compatible exports

I understand that ESM modules are less “compatible”, but they’re clearly the best way to build and distribute libraries going forward. See this explanation by [Sindre Sorhus](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).

**Comment by joepie91** [comment]
I am aware of their explanations; unfortunately, they are incorrect, as [ES modules are in many ways worse](https://gist.github.com/joepie91/bca2fda868c1e8b2c2caf76af7dfcad3), and do not fully replace the functionality of CommonJS modules. I have [attempted to bring this up with them](https://github.com/sindresorhus/p-defer/issues/7#issuecomment-864476408), unfortunately without result.
