### ISSUE TITLE
get decode length

### ISSUE THREAD

**Issue by missinglink** [joeltg/big-varint#2]
Heya,

Would you be open to me adding a couple lines of code to expose the amount of bytes read from `decode()` and the number of bytes written using `encode()`?

It's currently not possible to pass in a buffer containing several varints and know where the offsets lie in the buffer for the second and subsequent values.

The `npm varint` module has an elegant solution which could be implemented without breaking compatibility:
https://github.com/chrisdickinson/varint/blob/master/decode.js#L26

**Comment by joeltg** [comment]
You can do this now by calling `encodingLength(n)` for every `n` you decode. There are basically three common approaches to this in different libraries:

1. decode always returns a tuple containing both the decoded value and number of bytes read
2. the library writes the number of bytes read to a global variable that the user can access
3. the user can deterministically derive the encoded length from the returned value (ie calling `encodingLength()`)

I wish there was a simple best option but they are all a little awkward in one way or another. If 3) is shown to be significantly worse in terms of performance I would consider adding support for 2) like you asked, but for now just call `encodingLength`.

**Comment by missinglink** [comment]
Thanks for your reply @joeltg 

I would like to use this library in a hot code path so I'd like to avoid calling `encodingLength()` twice for every encode/decode operation, although I haven't benchmarked the performance, it's not necessary and must have *some* cost.

IMO the ergonomics of calling `encodingLength()` on the value returned from `decode()` are a little awkward, TBH it didn't occur to me.

Anyhoo, I just wanted to check if you'd accept a PR for 2), sounds like maybe you're happy with it as-is so I can make a fork instead.

**Comment by joeltg** [comment]
Added in 80f8852004f92eb15e212eafaac5af60355cef8a

**Comment by missinglink** [comment]
Awesome thanks!

Sorry to be a pain but would it be possible to add it for `encode()` too since it's [doing the calculation internally](https://github.com/joeltg/big-varint/blob/main/src/unsigned.ts#L22) already?

**Comment by joeltg** [comment]
oh shoot that's a bug, it's supposed to return a `Uint8Array` of exactly the encoded region (ie `byteLength` bytes long)

**Comment by joeltg** [comment]
fixed in v0.2.1

**Comment by missinglink** [comment]
agh I see, ok, so I'm assuming that `new Uint8Array()` doesn't allocate new memory when passed an existing `TypedArray` as the first argument?

**Comment by joeltg** [comment]
for encode, your options are

1) `encode(value: bigint)`, which allocates a new ArrayBuffer of exactly `encodingLength(value)` bytes, and returns a `Uint8Array` spanning those encoded bytes.
2) `encode(value: bigint, arrayBuffer: ArrayBuffer, byteOffset: number)`. the second argument must be an ArrayBuffer (**not** a Uint8Array or Dataview etc). this returns a `Uint8Array` spanning exactly the encoded bytes.

so for example

```ts
import { encode } from "big-varint/unsigned"

// big ArrayBuffer
const arrayBuffer = new ArrayBuffer(4096)

// encode into the ArrayBuffer starting at offset 8
const result = encode(123456789012345678901234567890n, arrayBuffer, 8)

// result is a Uint8Array that starts at offset 8 has byteLength 14
assert(result.buffer === arrayBuffer)
assert(result.byteOffset === 8)
assert(result.byteLength === 14)
```

**Comment by joeltg** [comment]
to answer your question, yes, the Uint8Array constructor will never allocate new memory if given an existing ArrayBuffer as the first argument

**Comment by missinglink** [comment]
ok cool thanks!

I also noticed that there is a rare edge-case if someone calls `encode()` with an `undefined` buffer but non-zero `byteOffset`.

In that case it will allocate a new buffer but then slice it wrong, although I doubt anyone will notice 😆

**Comment by joeltg** [comment]
Yes, that will throw an error, which is the correct behavior 😛
